// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAErwsgnckpco_Tnm4rl9fgFIpHcnmBx0o',
    appId: '1:352944254709:web:262feb78f421a3c7b95fbc',
    messagingSenderId: '352944254709',
    projectId: 'capstone-29ebb',
    authDomain: 'capstone-29ebb.firebaseapp.com',
    databaseURL: 'https://capstone-29ebb-default-rtdb.firebaseio.com',
    storageBucket: 'capstone-29ebb.appspot.com',
    measurementId: 'G-YXKB0WKZF6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlYqI0fEoJc77Kc1k9PeClIvq5krHzxnE',
    appId: '1:352944254709:android:12b7619a898c7531b95fbc',
    messagingSenderId: '352944254709',
    projectId: 'capstone-29ebb',
    databaseURL: 'https://capstone-29ebb-default-rtdb.firebaseio.com',
    storageBucket: 'capstone-29ebb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCc3431BNKmiKkiefQ-C8rCxZf76Um-SGQ',
    appId: '1:352944254709:ios:2aff487b2ac4216db95fbc',
    messagingSenderId: '352944254709',
    projectId: 'capstone-29ebb',
    databaseURL: 'https://capstone-29ebb-default-rtdb.firebaseio.com',
    storageBucket: 'capstone-29ebb.appspot.com',
    iosClientId: '352944254709-9ujpjb72rgj7amssnhr29v5kqq4jkodb.apps.googleusercontent.com',
    iosBundleId: 'capstone',
  );
}
